### PR TITLE
Fixed error when removing file selection

### PR DESCRIPTION
**Pull request by maryum375**
When selecting a file and then removing the selection onChangeEvent.target.files[0] was undefined, and therefore accessing the name of the first file through "cannot read property 'name' of undefined". Now the change function checks whether there is selection

### CODE REVIEW

**Comment by bahaaldine** [comment]
thanks for this @maryum375

**Comment by maryum375** [comment]
Thank you! :)
BTW, Why didn't it assigned me as a contributor to the repo?

**Comment by bahaaldine** [comment]
I honestly have no idea why ...

**Comment by bahaaldine** [comment]
I just merge another pull request and the same happened, strange ...

**Pull request merged**
